id: P003025
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG4474
  title: རྒྱལ་བ་ཚངས་དབྱངས་རྒྱ་མཚོའི་མགུར་གླུ
  author: ''
  volumes:
    b4c559be311f4551824289b449f2ede1:
      image_group_id: I1KG4504
      title: ''
      volume_number: 1
      total_pages: 22
      base_file: v001.txt
